### ISSUE TITLE
Marbles on the skins preview page reflect in the water

### ISSUE THREAD

**Issue by Zemanzo** [Zemanzo/web-marbles#276]
**Expected behavior**
Marbles on the skins page should not reflect in the water.

**Actual behavior**
Marbles on the skins page should reflect in the water, causing performance issues akin to #154.

**Reproduction steps**
1. Go to `/skins`.
2. Get the reflection of the marbles on screen.
3. Move around the camera view a bit.
4. Move it back to the horizon, see strange black reflections stuck to the viewport.

**Platform**
OS: Windows 10 (64-bit)
Browser version: Firefox Developer Edition 76.0b5 (64-bit)
Build version: `dev`, not in the current live version (`1.3.1`).

**Comment by Qaomen** [comment]
This issue describes two bugs: The marbles are reflected in the water on the `/skins` page when they shouldn't, and water reflection is causing huge performance issues and doesn't appear to clear correctly.

The latter may be caused by the updated `three.js` dependency somehow, since the reflected marbles on the skins page is in the live version as well.
